### ISSUE TITLE
Set Strip Parameter in VoiceMeeter Extension won't work

### ISSUE THREAD

**Issue by ProfWardenclyffe** [rivafarabi/deckboard-extensions#1]
No matter which version of VoiceMeeter is used, the selection of the strip number is not possible.
The only choice always remains the parameter 0, which is the first strip.

**Comment by terenc3** [comment]
This issue was resolved in the voicemeeter-control repository rivafarabi/voicemeeter-control#4

**Comment by rivafarabi** [comment]
closing this due inactivity and extension related issue
